package co.edu.javeriana.bigtexts.client.view;

import javax.swing.JButton;

/**
 * Vista de la pantalla Home
 *
 * @author Wilson Alzate Calderón <walzate@javeriana.edu.co>
 */
public class HomeView extends AbstractView {

    /**
     * Creates new form Home
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        startButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        imageJaveriana = new javax.swing.JLabel();
        legend1 = new javax.swing.JLabel();
        legend2 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BigTexts:Home");

        startButton.setText("Iniciar");
        startButton.setToolTipText("Start");

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoBigTexts.png"))); // NOI18N

        imageJaveriana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/javerianaNegro.png"))); // NOI18N

        legend1.setText("<html>Bienvenido!<br/>BigTexts es un framework de pre-procesamiento de datos en minería de texto <br/>basado en tecnologías de BigData</html>");

        legend2.setText("<html><p><strong>Por:</strong><br/> Ing. Wilson Alzate Calderón<br/><a href=\"mailto:walzate@javeriana.edu.co?Subject=BigTexts\" target=\"_top\">walzate@javeriana.edu.co</a></p><br/><p><strong>Directora:</strong><br/> Ing. Alexandra Pomares Quimbaya PhD<br/><a href=\"mailto:pomares@javeriana.edu.co?Subject=BigTexts\" target=\"_top\">pomares@javeriana.edu.co</a></p><br/><p><strong>Pontificia Universidad Javeriana</strong><br/>Facultad De Ingeniería<br/>Maestría en Ingeniería de Sistemas Y Computación - MISyC<br/>Bogotá DC, Colombia<br/>Diciembre de 2014</p> </html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(legend1)
                    .addComponent(legend2))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(startButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageJaveriana)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(imageJaveriana)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(legend1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(legend2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @return
     */
    public JButton getStartButton() {
        return startButton;
    }

    /**
     *
     * @param startButton
     */
    public void setStartButton(JButton startButton) {
        this.startButton = startButton;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageJaveriana;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel legend1;
    private javax.swing.JLabel legend2;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
