package co.edu.javeriana.bigtexts.client.view;

import co.edu.javeriana.bigtexts.client.model.AbstractModel;
import co.edu.javeriana.bigtexts.dto.PreprocessingTask;
import co.edu.javeriana.bigtexts.dto.PreprocessingTasksCatalog;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 * Clase con la vista de la pantalla de selección de tareas de preprocesamiento
 *
 * @author Wilson Alzate Calderón <walzate@javeriana.edu.co>
 */
public class SelectPreprocessingTasksView extends AbstractView {

    /**
     * Creates new form SelectPreprocessingTasks
     */
    public SelectPreprocessingTasksView() {
        initComponents();
        PreprocessingTasksCatalog catalog = AbstractModel.getPreprocessingTasksCatalog();
        if (catalog != null) {
            List<PreprocessingTask> preprocessingTasks = catalog.getPreprocessingTasks();
            for (PreprocessingTask task : preprocessingTasks) {
                sourceDefaultListModel.addElement(task.getName());
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se ha encontrado el catálogo de tareas de preprocesamiento", "", JOptionPane.ERROR_MESSAGE);
        }
        parametersPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        continueButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        preProcessingTasksPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sourceTasksList = new javax.swing.JList();
        leftAllButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        rightAllButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        targetTasksList = new javax.swing.JList();
        upTaskButton = new javax.swing.JButton();
        downTaskButton = new javax.swing.JButton();
        parametersPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        acceptButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        parametersTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BigTexts:Seleccionar tareas de pre-procesamiento");

        continueButton.setText("Continuar");

        returnButton.setText("Volver");

        preProcessingTasksPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Tareas de pre-procesamiento"));

        sourceTasksList.setModel(sourceDefaultListModel);
        jScrollPane1.setViewportView(sourceTasksList);

        leftAllButton.setText("<<");

        leftButton.setText("<");

        rightButton.setText("<html>&gt;</html>");

        rightAllButton.setText("<html>&gt;&gt;</html>");

        targetTasksList.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(targetTasksList);

        upTaskButton.setText("Arriba");

        downTaskButton.setText("Abajo");

        javax.swing.GroupLayout preProcessingTasksPanelLayout = new javax.swing.GroupLayout(preProcessingTasksPanel);
        preProcessingTasksPanel.setLayout(preProcessingTasksPanelLayout);
        preProcessingTasksPanelLayout.setHorizontalGroup(
            preProcessingTasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preProcessingTasksPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(preProcessingTasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(preProcessingTasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(leftAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rightAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(preProcessingTasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        preProcessingTasksPanelLayout.setVerticalGroup(
            preProcessingTasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preProcessingTasksPanelLayout.createSequentialGroup()
                .addGroup(preProcessingTasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(preProcessingTasksPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(preProcessingTasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preProcessingTasksPanelLayout.createSequentialGroup()
                                .addComponent(leftAllButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(leftButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rightAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))
                    .addGroup(preProcessingTasksPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(upTaskButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downTaskButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametrización de la tarea XXX"));

        cancelButton.setText("Cancelar");

        acceptButton.setText("Aceptar");

        parametersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Valor", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        parametersTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(parametersTable);
        if (parametersTable.getColumnModel().getColumnCount() > 0) {
            parametersTable.getColumnModel().getColumn(0).setMinWidth(200);
            parametersTable.getColumnModel().getColumn(1).setMinWidth(200);
            parametersTable.getColumnModel().getColumn(2).setMinWidth(1000);
        }

        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parametersPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        parametersPanelLayout.setVerticalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(acceptButton))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel1.setText("<html><h2><center><font face=\"tahoma\">Paso 2 de 3:<br/> Seleccionar y configurar<br/> tareas de pre-procesamiento</font></center></h2></html>");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoBigTexts.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/javerianaNegro.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preProcessingTasksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parametersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(continueButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(returnButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)))
                .addComponent(preProcessingTasksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continueButton)
                    .addComponent(returnButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @return
     */
    public JButton getContinueButton() {
        return continueButton;
    }

    /**
     *
     * @param continueButton
     */
    public void setContinueButton(JButton continueButton) {
        this.continueButton = continueButton;
    }

    /**
     *
     * @return
     */
    public JButton getReturnButton() {
        return returnButton;
    }

    /**
     *
     * @param returnButton
     */
    public void setReturnButton(JButton returnButton) {
        this.returnButton = returnButton;
    }

    /**
     *
     * @return
     */
    public JButton getLeftAllButton() {
        return leftAllButton;
    }

    /**
     *
     * @param leftAllButton
     */
    public void setLeftAllButton(JButton leftAllButton) {
        this.leftAllButton = leftAllButton;
    }

    /**
     *
     * @return
     */
    public JButton getLeftButton() {
        return leftButton;
    }

    /**
     *
     * @param leftButton
     */
    public void setLeftButton(JButton leftButton) {
        this.leftButton = leftButton;
    }

    /**
     *
     * @return
     */
    public JButton getRightAllButton() {
        return rightAllButton;
    }

    /**
     *
     * @param rightAllButton
     */
    public void setRightAllButton(JButton rightAllButton) {
        this.rightAllButton = rightAllButton;
    }

    /**
     *
     * @return
     */
    public JButton getRightButton() {
        return rightButton;
    }

    /**
     *
     * @param rightButton
     */
    public void setRightButton(JButton rightButton) {
        this.rightButton = rightButton;
    }

    /**
     *
     * @return
     */
    public JList getSourceTasksList() {
        return sourceTasksList;
    }

    /**
     *
     * @param sourceTasksList
     */
    public void setSourceTasksList(JList sourceTasksList) {
        this.sourceTasksList = sourceTasksList;
    }

    /**
     *
     * @return
     */
    public JList getTargetTasksList() {
        return targetTasksList;
    }

    /**
     *
     * @param targetTasksList
     */
    public void setTargetTasksList(JList targetTasksList) {
        this.targetTasksList = targetTasksList;
    }

    /**
     *
     * @return
     */
    public JButton getDownTaskButton() {
        return downTaskButton;
    }

    /**
     *
     * @param downTaskButton
     */
    public void setDownTaskButton(JButton downTaskButton) {
        this.downTaskButton = downTaskButton;
    }

    /**
     *
     * @return
     */
    public JButton getUpTaskButton() {
        return upTaskButton;
    }

    /**
     *
     * @param upTaskButton
     */
    public void setUpTaskButton(JButton upTaskButton) {
        this.upTaskButton = upTaskButton;
    }

    /**
     *
     * @return
     */
    public JPanel getParametersPanel() {
        return parametersPanel;
    }

    /**
     *
     * @param parametersPanel
     */
    public void setParametersPanel(JPanel parametersPanel) {
        this.parametersPanel = parametersPanel;
    }

    /**
     *
     * @return
     */
    public JTable getParametersTable() {
        return parametersTable;
    }

    /**
     *
     * @param parametersTable
     */
    public void setParametersTable(JTable parametersTable) {
        this.parametersTable = parametersTable;
    }

    /**
     *
     * @return
     */
    public JButton getCancelButton() {
        return cancelButton;
    }

    /**
     *
     * @param cancelButton
     */
    public void setCancelButton(JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     *
     * @return
     */
    public JButton getAcceptButton() {
        return acceptButton;
    }

    /**
     *
     * @param acceptButton
     */
    public void setAcceptButton(JButton acceptButton) {
        this.acceptButton = acceptButton;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JButton downTaskButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton leftAllButton;
    private javax.swing.JButton leftButton;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JTable parametersTable;
    private javax.swing.JPanel preProcessingTasksPanel;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton rightAllButton;
    private javax.swing.JButton rightButton;
    private javax.swing.JList sourceTasksList;
    private javax.swing.JList targetTasksList;
    private javax.swing.JButton upTaskButton;
    // End of variables declaration//GEN-END:variables
    private DefaultListModel sourceDefaultListModel = new DefaultListModel();
}
