package co.edu.javeriana.bigtexts.client.view;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Clase con la pantalla de carga de archivos
 *
 * @author Wilson Alzate Calderón <walzate@javeriana.edu.co>
 */
public class UploadDocumentsView extends AbstractView {

    /**
     * Creates new form UploadDocuments
     */
    public UploadDocumentsView() {
        initComponents();
        fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setDialogTitle("Seleccionar los documentos fuente");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        documentsPathLabel = new javax.swing.JLabel();
        selectFileButton = new javax.swing.JButton();
        uploadFileButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        documentsPathTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        uploadedDocumentsTable = new javax.swing.JTable();
        progressLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        continueButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BigTexts:Cargar Documentos");

        documentsPathLabel.setText("Fuente de documentos: ");

        selectFileButton.setText("Seleccionar...");

        uploadFileButton.setText("Cargar");
        uploadFileButton.setEnabled(false);

        cancelButton.setText("Cancelar");

        uploadedDocumentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre", "Peso (Kb)"
            }
        ));
        jScrollPane1.setViewportView(uploadedDocumentsTable);

        progressLabel.setText("Progreso");

        continueButton.setText("Continuar");

        jLabel1.setText("<html><h2><center><font face=\"Tahoma\">Paso 1 de 3:<br/> Cargar Documentos</font></center></h2></html>");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoBigTexts.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/javerianaNegro.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(documentsPathLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(documentsPathTextField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(uploadFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selectFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel2)
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(71, 71, 71)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentsPathLabel)
                    .addComponent(documentsPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(uploadFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(continueButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @return
     */
    public JButton getCancelButton() {
        return cancelButton;
    }

    /**
     *
     * @param cancelButton
     */
    public void setCancelButton(JButton cancelButton) {
        this.cancelButton = cancelButton;
    }

    /**
     *
     * @return
     */
    public JButton getSelectFileButton() {
        return selectFileButton;
    }

    /**
     *
     * @param selectFileButton
     */
    public void setSelectFileButton(JButton selectFileButton) {
        this.selectFileButton = selectFileButton;
    }

    /**
     *
     * @return
     */
    public JButton getUploadFileButton() {
        return uploadFileButton;
    }

    /**
     *
     * @param uploadFileButton
     */
    public void setUploadFileButton(JButton uploadFileButton) {
        this.uploadFileButton = uploadFileButton;
    }

    /**
     *
     * @return
     */
    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    /**
     *
     * @param fileChooser
     */
    public void setFileChooser(JFileChooser fileChooser) {
        this.fileChooser = fileChooser;
    }

    /**
     *
     * @return
     */
    public JTextField getDocumentsPathTextField() {
        return documentsPathTextField;
    }

    /**
     *
     * @param documentsPathTextField
     */
    public void setDocumentsPathTextField(JTextField documentsPathTextField) {
        this.documentsPathTextField = documentsPathTextField;
    }

    /**
     *
     * @return
     */
    public JTable getUploadedDocumentsTable() {
        return uploadedDocumentsTable;
    }

    /**
     *
     * @param uploadedDocumentsTable
     */
    public void setUploadedDocumentsTable(JTable uploadedDocumentsTable) {
        this.uploadedDocumentsTable = uploadedDocumentsTable;
    }

    /**
     *
     * @return
     */
    public JButton getContinueButton() {
        return continueButton;
    }

    /**
     *
     * @param continueButton
     */
    public void setContinueButton(JButton continueButton) {
        this.continueButton = continueButton;
    }

    public JProgressBar getProgressBar() {
        return progressBar;
    }

    public void setProgressBar(JProgressBar progressBar) {
        this.progressBar = progressBar;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel documentsPathLabel;
    private javax.swing.JTextField documentsPathTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JButton selectFileButton;
    private javax.swing.JButton uploadFileButton;
    private javax.swing.JTable uploadedDocumentsTable;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JFileChooser fileChooser;
}
